### ISSUE TITLE
Why can't I put the pictures of multiple folders that have been classified into the \mbnetv1_dataset\ this folder?

### ISSUE THREAD

**Issue by lbmcu** [sipeed/Maix-EMC#2]
Why can't I put the pictures of multiple folders that have been classified into the \mbnetv1_dataset\ this folder????

**Comment by lbmcu** [comment]
I put some pictures in that folder is right,but When I put many folder and every folder have classificated pictures ,then display this error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbnetv1_to_kmodel.py", line 14, in <module>
    emc.save_kmodel(mobilenetv1, kmodel_name, './mbnetv1_dataset', dataset_func='img_0_1', quant_func='minmax', quant_bit=8, version=3, sm_flag=True)
  File "/home/long/anaconda3/envs/TensorFlow/lib/python3.7/site-packages/maixemc/edge_model.py", line 330, in save_kmodel
    raise RuntimeError("save kmodel error")
RuntimeError: save kmodel error


What I need to do this many folder with pictures??
